sudo: required

language: python

python:
  - 3.6

services:
  - docker

script:
  - true # TODO: write some tests

before_deploy:
  - docker build -t aws-lambda-pdf2jpg .
  - docker run --rm -v "$PWD":/var/task aws-lambda-pdf2jpg
